### ISSUE TITLE
Calendar onConfirm 这里关闭后state的值就设置空了。回调拿不到值

### ISSUE THREAD

**Issue by tinys** [react-component/m-calendar#2]
onConfirm = () => {
    this.onClose();
    const { onConfirm } = this.props;
    let { startDate, endDate } = this.state;
    if (startDate && endDate && +startDate > +endDate) {
      return onConfirm && onConfirm(endDate, startDate);
    }
    onConfirm && onConfirm(startDate, endDate);
  }

帮忙看下

**Comment by zhang740** [comment]
测试没有问题，更新了demo代码会打印出时间，你可以看下，提供下具体的例子？

**Comment by tinys** [comment]
哦 基于preact下会有问题。

**Comment by zhang740** [comment]
更新下试试 0.1.14
